services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./spotsat_back/.env.test
 
  node:
    image: spotsat_back
    build:
      context: .
      dockerfile: ./spotsat_back/Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres  
    env_file:
      - ./spotsat_back/.env.test